using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.Maui.AI.Indexer.Generators.Models;

namespace Microsoft.Maui.AI.Indexer.Generators.Generation;

/// <summary>
/// Emits the aggregate {AssemblyName}UiIndex : UiPageIndex class
/// with a Default singleton and Pages override.
/// </summary>
internal static class AggregateCodeEmitter
{
    public static string Emit(ProjectIndex index, string? rootNamespace)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Validate namespace
        var safeNamespace = IsValidCSharpNamespace(rootNamespace) ? rootNamespace : null;

        if (!string.IsNullOrEmpty(safeNamespace))
        {
            sb.AppendLine($"namespace {safeNamespace};");
            sb.AppendLine();
        }

        // Class name derived from assembly name (sanitized)
        var className = SanitizeIdentifier(rootNamespace ?? "App") + "UiIndex";

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated UI page index for this assembly. Provides access to all");
        sb.AppendLine("/// indexed XAML pages and their semantic markdown content.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial class {className} : global::Microsoft.Maui.AI.Indexer.UiPageIndex");
        sb.AppendLine("{");

        // Default singleton
        sb.AppendLine($"    /// <summary>The default instance.</summary>");
        sb.AppendLine($"    public static {className} Default {{ get; }} = new();");
        sb.AppendLine();

        // Pages override
        sb.AppendLine("    private static readonly global::Microsoft.Maui.AI.Indexer.UiPageEntry[] s_pages = new global::Microsoft.Maui.AI.Indexer.UiPageEntry[]");
        sb.AppendLine("    {");

        foreach (var page in index.Pages.OrderBy(p => p.ClassName))
        {
            var route = page.Route != null ? $"\"{Escape(page.Route)}\"" : "null";
            var filePath = !string.IsNullOrEmpty(page.FilePath) ? $"\"{Escape(page.FilePath)}\"" : "null";
            var fqnClass = !string.IsNullOrEmpty(page.Namespace)
                ? $"global::{page.Namespace}.{SanitizeIdentifier(page.ClassName)}_UiIndex"
                : $"global::{SanitizeIdentifier(page.ClassName)}_UiIndex";

            sb.AppendLine($"        new global::Microsoft.Maui.AI.Indexer.UiPageEntry(\"{Escape(page.ClassName)}\", {route}, {filePath}, {fqnClass}.Markdown),");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public override global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Maui.AI.Indexer.UiPageEntry> Pages => s_pages;");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var ch in name)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
                sb.Append(ch);
            else
                sb.Append('_');
        }
        return sb.ToString();
    }

    private static bool IsValidCSharpNamespace(string? ns)
    {
        if (string.IsNullOrWhiteSpace(ns))
            return false;

        foreach (var part in ns!.Split('.'))
        {
            if (part.Length == 0)
                return false;
            if (!char.IsLetter(part[0]) && part[0] != '_')
                return false;
            foreach (var ch in part)
            {
                if (!char.IsLetterOrDigit(ch) && ch != '_')
                    return false;
            }
        }
        return true;
    }
}
