using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.Maui.AI.Indexer.Generators.Models;

namespace Microsoft.Maui.AI.Indexer.Generators.Generation;

/// <summary>Emits the aggregate UiIndex.g.cs file with search capability.</summary>
internal static class AggregateCodeEmitter
{
    public static string Emit(ProjectIndex index, string? rootNamespace)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();

        // Validate namespace — assembly names can contain invalid C# chars
        var safeNamespace = IsValidCSharpNamespace(rootNamespace) ? rootNamespace : null;

        if (!string.IsNullOrEmpty(safeNamespace))
        {
            sb.AppendLine($"namespace {safeNamespace};");
            sb.AppendLine();
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Aggregate UI index — provides discovery and search across all indexed pages.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::Microsoft.Maui.AI.Indexer.UiProjectIndex]");
        sb.AppendLine("public static partial class UiIndex");
        sb.AppendLine("{");

        // Page entry record
        sb.AppendLine("    /// <summary>Represents an indexed page.</summary>");
        sb.AppendLine("    public sealed class PageEntry");
        sb.AppendLine("    {");
        sb.AppendLine("        public PageEntry(string name, string? route, string? filePath, string markdown)");
        sb.AppendLine("        {");
        sb.AppendLine("            Name = name;");
        sb.AppendLine("            Route = route;");
        sb.AppendLine("            FilePath = filePath;");
        sb.AppendLine("            Markdown = markdown;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public string Name { get; }");
        sb.AppendLine("        public string? Route { get; }");
        sb.AppendLine("        public string? FilePath { get; }");
        sb.AppendLine("        public string Markdown { get; }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Static pages array
        sb.AppendLine("    /// <summary>All indexed pages.</summary>");
        sb.AppendLine("    public static readonly PageEntry[] Pages = new PageEntry[]");
        sb.AppendLine("    {");

        foreach (var page in index.Pages.OrderBy(p => p.ClassName))
        {
            var route = page.Route != null ? $"\"{Escape(page.Route)}\"" : "null";
            var filePath = !string.IsNullOrEmpty(page.FilePath) ? $"\"{Escape(page.FilePath)}\"" : "null";
            var className = SanitizeIdentifier(page.ClassName);
            var fqn = !string.IsNullOrEmpty(page.Namespace)
                ? $"global::{page.Namespace}.{className}_UiIndex"
                : $"global::{className}_UiIndex";

            sb.AppendLine($"        new PageEntry(\"{Escape(page.ClassName)}\", {route}, {filePath}, {fqn}.Markdown),");
        }

        sb.AppendLine("    };");
        sb.AppendLine();

        // Search method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Search across all page indexes for pages containing the given text.");
        sb.AppendLine("    /// Returns matching pages with their markdown content.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static PageEntry[] Search(string query)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(query))");
        sb.AppendLine("            return Pages;");
        sb.AppendLine();
        sb.AppendLine("        return Pages");
        sb.AppendLine("            .Where(p => p.Markdown.Contains(query, StringComparison.OrdinalIgnoreCase)");
        sb.AppendLine("                     || p.Name.Contains(query, StringComparison.OrdinalIgnoreCase)");
        sb.AppendLine("                     || (p.Route != null && p.Route.Contains(query, StringComparison.OrdinalIgnoreCase)))");
        sb.AppendLine("            .ToArray();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Find by route
        sb.AppendLine("    /// <summary>Find a page by its Shell route.</summary>");
        sb.AppendLine("    public static PageEntry? FindByRoute(string route)");
        sb.AppendLine("    {");
        sb.AppendLine("        return Pages.FirstOrDefault(p => string.Equals(p.Route, route, StringComparison.OrdinalIgnoreCase));");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Find by name
        sb.AppendLine("    /// <summary>Find a page by its class name.</summary>");
        sb.AppendLine("    public static PageEntry? FindByName(string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        return Pages.FirstOrDefault(p => string.Equals(p.Name, name, StringComparison.OrdinalIgnoreCase));");
        sb.AppendLine("    }");
        sb.AppendLine();

        // All markdown concatenated (for full-corpus search)
        sb.AppendLine("    /// <summary>All page markdown concatenated, separated by page breaks.</summary>");
        sb.AppendLine("    public static string AllMarkdown => string.Join(\"\\n\\n---\\n\\n\", Pages.Select(p => p.Markdown));");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var ch in name)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
                sb.Append(ch);
            else
                sb.Append('_');
        }
        return sb.ToString();
    }

    private static bool IsValidCSharpNamespace(string? ns)
    {
        if (string.IsNullOrWhiteSpace(ns))
            return false;

        foreach (var part in ns!.Split('.'))
        {
            if (part.Length == 0)
                return false;
            if (!char.IsLetter(part[0]) && part[0] != '_')
                return false;
            foreach (var ch in part)
            {
                if (!char.IsLetterOrDigit(ch) && ch != '_')
                    return false;
            }
        }
        return true;
    }
}
