using System.Text;
using Microsoft.Maui.AI.Indexer.Generators.Models;

namespace Microsoft.Maui.AI.Indexer.Generators.Generation;

/// <summary>Emits a .g.cs file for a single XAML page with embedded markdown.</summary>
internal static class PageCodeEmitter
{
    public static string Emit(PageModel page)
    {
        var markdown = MarkdownBuilder.RenderPage(page);
        var (escapedMarkdown, delimiter) = EscapeForRawStringLiteral(markdown);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(page.Namespace))
        {
            sb.AppendLine($"namespace {page.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// AI-generated UI index for {page.ClassName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static partial class {SanitizeIdentifier(page.ClassName)}_UiIndex");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Structured markdown representation of the page UI.</summary>");
        sb.AppendLine("    public const string Markdown =");
        sb.AppendLine($"        {delimiter}");

        // Indent each line of markdown by 8 spaces for clean formatting
        foreach (var line in escapedMarkdown.Split('\n'))
        {
            var trimmed = line.TrimEnd('\r');
            if (trimmed.Length == 0)
                sb.AppendLine();
            else
                sb.AppendLine("        " + trimmed);
        }

        sb.AppendLine($"        {delimiter};");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>The page class name.</summary>");
        sb.AppendLine($"    public const string PageName = \"{Escape(page.ClassName)}\";");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static (string text, string delimiter) EscapeForRawStringLiteral(string text)
    {
        // Raw string literals use """ as delimiter. If the text contains """,
        // we need a longer delimiter ("""" ... """").
        var delimiter = "\"\"\"";
        var testSequence = "\"\"\"";
        while (text.Contains(testSequence))
        {
            delimiter += "\"";
            testSequence += "\"";
        }
        return (text, delimiter);
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var ch in name)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
                sb.Append(ch);
            else
                sb.Append('_');
        }
        return sb.ToString();
    }
}
