using System.Text;
using Microsoft.Maui.AI.Indexer.Generators.Models;

namespace Microsoft.Maui.AI.Indexer.Generators.Generation;

/// <summary>Emits a .g.cs file for a single XAML page with embedded markdown.</summary>
internal static class PageCodeEmitter
{
    public static string Emit(PageModel page)
    {
        var markdown = MarkdownBuilder.RenderPage(page);
        var escapedMarkdown = EscapeForRawStringLiteral(markdown);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(page.Namespace))
        {
            sb.AppendLine($"namespace {page.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// AI-generated UI index for {page.ClassName}.");
        sb.AppendLine("/// </summary>");

        var routeAttr = page.Route != null ? $", Route = \"{Escape(page.Route)}\"" : "";
        var fileAttr = !string.IsNullOrEmpty(page.FilePath) ? $", FilePath = \"{Escape(page.FilePath)}\"" : "";

        sb.AppendLine($"[global::Microsoft.Maui.AI.Indexer.UiPageIndex(\"{Escape(page.ClassName)}\"{routeAttr}{fileAttr})]");
        sb.AppendLine($"public static partial class {SanitizeIdentifier(page.ClassName)}_UiIndex");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Structured markdown representation of the page UI.</summary>");
        sb.AppendLine("    public const string Markdown =");
        sb.AppendLine("        \"\"\"");

        // Indent each line of markdown by 8 spaces for clean formatting
        foreach (var line in escapedMarkdown.Split('\n'))
        {
            var trimmed = line.TrimEnd('\r');
            if (trimmed.Length == 0)
                sb.AppendLine();
            else
                sb.AppendLine("        " + trimmed);
        }

        sb.AppendLine("        \"\"\";");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>The page class name.</summary>");
        sb.AppendLine($"    public const string PageName = \"{Escape(page.ClassName)}\";");

        if (page.Route != null)
        {
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>The Shell route for this page.</summary>");
            sb.AppendLine($"    public const string Route = \"{Escape(page.Route)}\";");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeForRawStringLiteral(string text)
    {
        // Raw string literals (""") don't need escaping except for the closing sequence
        // If the text contains """, we'd need more quotes, but this is extremely unlikely
        return text;
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var ch in name)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
                sb.Append(ch);
            else
                sb.Append('_');
        }
        return sb.ToString();
    }
}
