using System.Text.Json;
using System.Text.Json.Serialization;

namespace Microsoft.Maui.DevFlow.Testing;

/// <summary>Source-generated JSON metadata for non-executable DevFlow testing contracts.</summary>
[JsonSourceGenerationOptions(
    GenerationMode = JsonSourceGenerationMode.Metadata,
    PropertyNameCaseInsensitive = true,
    WriteIndented = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(MauiTestPlan))]
[JsonSerializable(typeof(MauiFlowRepairPolicy))]
[JsonSerializable(typeof(MauiFlowSideEffectPolicy))]
[JsonSerializable(typeof(MauiFlowRunRequest))]
[JsonSerializable(typeof(MauiFlowRunContext))]
[JsonSerializable(typeof(MauiFlowRunReport))]
[JsonSerializable(typeof(MauiFlowRunReport[]))]
[JsonSerializable(typeof(MauiTestExecutionManifest))]
[JsonSerializable(typeof(MauiTestExecutionHostFacts))]
[JsonSerializable(typeof(MauiTestExecutionBuildFacts))]
[JsonSerializable(typeof(MauiTestExecutionDeviceFacts))]
[JsonSerializable(typeof(MauiTestExecutionLifecycleFacts))]
[JsonSerializable(typeof(MauiTestExecutionLifecycleStage))]
[JsonSerializable(typeof(MauiTestExecutionArtifact))]
[JsonSerializable(typeof(MauiTestExecutionOutcomeFacts))]
[JsonSerializable(typeof(MauiFlowTriage))]
[JsonSerializable(typeof(MauiFlowTriageClassification))]
[JsonSerializable(typeof(MauiFlowTriageEvidenceSufficiency))]
[JsonSerializable(typeof(MauiFlowTriageExecutionFacts))]
[JsonSerializable(typeof(MauiFlowRunTarget))]
[JsonSerializable(typeof(MauiFlowResetResult))]
[JsonSerializable(typeof(MauiFlowResetReference))]
[JsonSerializable(typeof(MauiFlowResetOutcome))]
[JsonSerializable(typeof(MauiFlowAppStateSeedFingerprint))]
[JsonSerializable(typeof(MauiFlowBackendTestDataSeedFingerprint))]
[JsonSerializable(typeof(MauiFlowReplayPreconditions))]
[JsonSerializable(typeof(MauiFlowCheckpoint))]
[JsonSerializable(typeof(MauiFlowCompensatorReference))]
[JsonSerializable(typeof(MauiFlowCompensatorOutcome))]
[JsonSerializable(typeof(MauiIndependentBusinessOracleDeclaration))]
[JsonSerializable(typeof(MauiIndependentBusinessOracleResult))]
[JsonSerializable(typeof(MauiFlowReplayEligibilityDecision))]
[JsonSerializable(typeof(MauiFlowReplayEligibilityReason))]
[JsonSerializable(typeof(MauiFlowRunVerification))]
[JsonSerializable(typeof(MauiFlowRunOutcome))]
[JsonSerializable(typeof(MauiFlowRunEvent))]
[JsonSerializable(typeof(MauiFlowStepAttempt))]
[JsonSerializable(typeof(MauiFlowTargetResolution))]
[JsonSerializable(typeof(MauiFlowActionabilityAttempt))]
[JsonSerializable(typeof(MauiFlowDispatchReceipt))]
[JsonSerializable(typeof(MauiFlowAssertionResult))]
[JsonSerializable(typeof(MauiFlowValueDisclosure))]
[JsonSerializable(typeof(MauiFlowFailure))]
[JsonSerializable(typeof(MauiFlowSecondaryFailure))]
[JsonSerializable(typeof(MauiFlowAppProcessEvidence))]
[JsonSerializable(typeof(MauiFlowExpectedEvidenceReport))]
[JsonSerializable(typeof(MauiFlowExpectedEvidenceCheck))]
[JsonSerializable(typeof(MauiFlowArtifactReference))]
[JsonSerializable(typeof(MauiFlowReportOmission))]
[JsonSerializable(typeof(MauiElementFingerprint))]
[JsonSerializable(typeof(MauiSelectorCandidate))]
[JsonSerializable(typeof(MauiSelectorEvidence))]
[JsonSerializable(typeof(MauiSelectorHealthAnalysis))]
[JsonSerializable(typeof(MauiSelectorHealthFinding))]
[JsonSerializable(typeof(MauiSelectorCoverageSummary))]
[JsonSerializable(typeof(MauiFlowRepairProposal))]
[JsonSerializable(typeof(MauiFlowRepairOutcome))]
[JsonSerializable(typeof(MauiFlowPatch))]
[JsonSerializable(typeof(MauiFlowPatchOperation))]
[JsonSerializable(typeof(MauiRepairSelectorDiff))]
[JsonSerializable(typeof(MauiRepairAssertionProof))]
[JsonSerializable(typeof(MauiRepairUniquenessProof))]
[JsonSerializable(typeof(MauiRepairApproval))]
[JsonSerializable(typeof(MauiFlowRepairEligibilityDecision))]
[JsonSerializable(typeof(MauiFlowRepairEligibilityReason))]
[JsonSerializable(typeof(MauiRepairPriorSelectorResolution))]
[JsonSerializable(typeof(MauiRepairCandidateResolution))]
[JsonSerializable(typeof(MauiImportedArtifactIdentity))]
[JsonSerializable(typeof(MauiArtifactProvenanceSubject))]
[JsonSerializable(typeof(MauiArtifactVerifiedProvenanceFacts))]
[JsonSerializable(typeof(MauiArtifactTrustPolicy))]
[JsonSerializable(typeof(MauiArtifactIntegrityVerification))]
[JsonSerializable(typeof(MauiArtifactTrustReason))]
[JsonSerializable(typeof(MauiArtifactTrustOmission))]
[JsonSerializable(typeof(MauiArtifactTrustVerificationResult))]
[JsonSerializable(typeof(MauiImportedArtifactSafeProjection))]
[JsonSerializable(typeof(MauiImportedFailureProjection))]
[JsonSerializable(typeof(MauiArtifactTrustRecord))]
[JsonSerializable(typeof(MauiArtifactTrustStatus))]
[JsonSerializable(typeof(MauiLocalReproductionFacts))]
[JsonSerializable(typeof(MauiLocalFailureFacts))]
[JsonSerializable(typeof(MauiLocalReproductionExpectation))]
[JsonSerializable(typeof(MauiLocalReproductionBinding))]
[JsonSerializable(typeof(MauiLocalReproductionEvaluation))]
[JsonSerializable(typeof(MauiLocalReproductionReport))]
[JsonSerializable(typeof(MauiArtifactProposalDecision))]
[JsonSerializable(typeof(MauiFlowMigrationResult))]
[JsonSerializable(typeof(MauiFlowRequirements))]
[JsonSerializable(typeof(MauiFlowCapabilitySet))]
[JsonSerializable(typeof(MauiFlowRequirementValidation))]
[JsonSerializable(typeof(MauiPreviewQualificationInput))]
[JsonSerializable(typeof(MauiPreviewQualificationReport))]
[JsonSerializable(typeof(MauiQualificationAccumulation))]
[JsonSerializable(typeof(MauiQualificationCorpusSummary))]
[JsonSerializable(typeof(MauiQualificationFingerprints))]
[JsonSerializable(typeof(MauiQualificationMetrics))]
[JsonSerializable(typeof(List<MauiQualificationPlatformProfile>))]
[JsonSerializable(typeof(MauiQualificationAppleQaEvidence))]
[JsonSerializable(typeof(MauiQualificationExecutionSample))]
[JsonSerializable(typeof(MauiQualificationGateThresholds))]
[JsonSerializable(typeof(MauiQualificationRuntimeOverheadMetric))]
[JsonSerializable(typeof(MauiQualificationPrivacySecurityMetric))]
[JsonSerializable(typeof(MauiQualificationReviewEvidence))]
[JsonSerializable(typeof(MauiPreviewFeatureFlags))]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
public sealed partial class MauiTestingJsonContext : JsonSerializerContext;
