using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.Maui.Cli.DevFlow.Flows;
using Microsoft.Maui.Cli.UnitTests.Fixtures;
using Xunit;

namespace Microsoft.Maui.Cli.UnitTests;

/// <summary>
/// The published <c>devflow-ci-failure</c> issue carries only a one-way test-identity digest, so a
/// resolver that disagreed with the producer by a single byte would make every issue permanently
/// unactionable while looking correct. These tests pin the construction against the real producer
/// in <c>eng/devflow/New-DevFlowFailureHandoff.ps1</c> and pin the resolver's outcomes, including
/// the ones that must fail rather than guess.
/// </summary>
[Collection("CLI")]
public sealed class FlowIdentityCliTests : IDisposable
{
    private readonly string _root = Path.Combine(
        AppContext.BaseDirectory,
        "flow-identity-cli-tests",
        Guid.NewGuid().ToString("N"));

    public FlowIdentityCliTests() => Directory.CreateDirectory(_root);

    /// <summary>
    /// Generated by running <c>Get-TestIdentity</c> out of the committed producer script, not by
    /// hand. Regenerate with <c>eng/devflow/New-DevFlowFailureHandoff.ps1</c> if the construction
    /// ever changes; a changed construction is a breaking change to every published issue.
    /// </summary>
    public static TheoryData<string, string, string, string> ProducerVectors => new()
    {
        {
            "android", "tier-1",
            "sha256:0000000000000000000000000000000000000000000000000000000000000000",
            "sha256:dd5aaa3c0d5d7685cb6d9326e5adf33dba7ec56aa7c29f53fb848f974c7d2708"
        },
        {
            "android", "tier-1",
            "sha256:9caec2a77244930c5a527cbdc4e8131702f54b9bc2cf53807b6d0b5d1ab11e3e",
            "sha256:a57607aa7852215d0e29dba418936f26f105db570da2d0e2d561ae0e6841e75f"
        },
        {
            "ios", "tier-1",
            "sha256:abababababababababababababababababababababababababababababababab",
            "sha256:a305fa529918bf6b5de95cc6d2358325892ea3f4dde879f0e29c5b75e55ee6a5"
        },
        {
            "windows", "tier-1",
            "sha256:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
            "sha256:32af36d1754ff5aab1bee82deca2096e8f270c7a5530b66ea693b55855f46504"
        },
        {
            "android", "tier-1",
            "sha256:d29ef0c7ba89c338c3ae58f079b92e8c4ac8ed0ca161a57b68724def8195fd56",
            "sha256:f4000063dcee7c736b59f21b2f8e4b584f9aaa1109e3cc1a11b161b497fa3cdb"
        },
    };

    [Theory]
    [MemberData(nameof(ProducerVectors))]
    public void ComputeTestIdentity_ReproducesTheProducerDigest(
        string platform, string tier, string flowDigest, string expected)
    {
        Assert.Equal(expected, FlowIdentityCommands.ComputeTestIdentity(platform, tier, flowDigest));

        // The producer is handed the manifest digest verbatim, and its Test-Sha256 guard pins that
        // to the sha256:-prefixed form. Accepting the bare hex a caller gets from ComputeFlowDigest
        // has to reach the same digest, or the resolver would never match a real flow.
        Assert.Equal(expected, FlowIdentityCommands.ComputeTestIdentity(platform, tier, flowDigest[7..]));
    }

    /// <summary>
    /// The PowerShell <c>`n</c> escape is LF. Using <see cref="Environment.NewLine"/> on Windows
    /// would emit CRLF and silently produce a digest that can never match a published issue, so the
    /// difference is asserted rather than assumed.
    /// </summary>
    [Fact]
    public void ComputeTestIdentity_UsesLineFeedSeparatorsNotTheEnvironmentNewline()
    {
        const string Platform = "android";
        const string Tier = "tier-1";
        const string FlowDigest = "sha256:d29ef0c7ba89c338c3ae58f079b92e8c4ac8ed0ca161a57b68724def8195fd56";

        var identity = FlowIdentityCommands.ComputeTestIdentity(Platform, Tier, FlowDigest);
        Assert.Equal(Sha256Text($"devflow-ci-test-identity-v1\n{Platform}\n{Tier}\n{FlowDigest}"), identity);
        Assert.NotEqual(Sha256Text($"devflow-ci-test-identity-v1\r\n{Platform}\r\n{Tier}\r\n{FlowDigest}"), identity);
    }

    /// <summary>
    /// Round-trips against the committed producer itself. The three hashing functions are lifted
    /// out of <c>New-DevFlowFailureHandoff.ps1</c> by its own parser, so this asserts parity with
    /// the exact text CI runs rather than with a copy of it.
    /// </summary>
    [Theory]
    [MemberData(nameof(ProducerVectors))]
    public async Task ComputeTestIdentity_MatchesTheCommittedPowerShellProducer(
        string platform, string tier, string flowDigest, string expected)
    {
        var script = Path.Combine(FindRepositoryRoot(), "eng", "devflow", "New-DevFlowFailureHandoff.ps1");
        Assert.True(File.Exists(script), $"The producer script was not found at '{script}'.");

        var produced = await RunProducerIdentityAsync(script, platform, tier, flowDigest);
        if (produced is null)
        {
            // xUnit v2.9.3 has no dynamic skip. CI runs this suite on windows-latest and
            // macos-latest, both of which ship pwsh, so a null here on Windows means the producer
            // harness broke rather than that pwsh is genuinely absent - fail instead of going quiet.
            Assert.False(OperatingSystem.IsWindows(), "pwsh was expected to be available on Windows.");
            return; // pwsh is not installed; the pinned vectors still guard the construction
        }

        Assert.Equal(expected, produced);
        Assert.Equal(produced, FlowIdentityCommands.ComputeTestIdentity(platform, tier, flowDigest));
    }

    [Fact]
    public async Task FlowIdentity_ForACommittedFlow_ReportsTheDigestAndIdentity()
    {
        var directory = CreateDirectory("compute");
        var flow = await WriteFlowAsync(directory, "checkout", "Alpha");
        var cli = new CliTestHarness(mockAgentPort: 1);

        var result = await cli.InvokeRawAsync("devflow", "flow", "identity", flow, "--platform", "android", "--json");

        Assert.Equal(0, result.ExitCode);
        var root = result.ParseJsonOutput();
        Assert.True(root.GetProperty("ok").GetBoolean());
        Assert.Equal("compute", root.GetProperty("mode").GetString());
        Assert.Equal("devflow-flow-identity-v1", root.GetProperty("schema").GetString());
        Assert.Equal(["android"], root.GetProperty("platforms").EnumerateArray().Select(item => item.GetString()!).ToArray());

        var construction = root.GetProperty("construction");
        Assert.Equal("LF", construction.GetProperty("newline").GetString());
        Assert.Equal("utf-8", construction.GetProperty("encoding").GetString());
        Assert.Equal("eng/devflow/New-DevFlowFailureHandoff.ps1", construction.GetProperty("producer").GetString());

        var entry = Assert.Single(root.GetProperty("flows").EnumerateArray().ToList());
        // Golden values, generated from the real PowerShell producer for this fixture's bytes.
        // Pinning literals rather than re-deriving them here means this test also catches a change
        // to ComputeFlowDigest's canonicalisation, which would silently move every identity.
        Assert.Equal(
            "sha256:24019ac7757a767bbb3835cacb804bfdd5f397f43a87bbb623d2a27a3b649a3b",
            entry.GetProperty("flowDigest").GetString());
        var identity = Assert.Single(entry.GetProperty("identities").EnumerateArray().ToList());
        Assert.Equal("tier-1", identity.GetProperty("tier").GetString());
        Assert.Equal(
            "sha256:07f53fdfb72d53886c2647592b20ff7925ff2ef74c01f52ff6fa18af7a78f34e",
            identity.GetProperty("testIdentitySha256").GetString());
    }

    [Fact]
    public async Task FlowIdentity_Resolve_NamesTheCommittedFlowThatProducedTheIdentity()
    {
        var directory = CreateDirectory("resolve-match");
        await WriteFlowAsync(directory, "checkout", "Alpha");
        await WriteFlowAsync(directory, "search", "Beta");
        var identity = await ComputeIdentityAsync(directory, "checkout", "android");
        var cli = new CliTestHarness(mockAgentPort: 1);

        var result = await cli.InvokeRawAsync(
            "devflow", "flow", "identity", "--resolve", identity, "--search", directory, "--platform", "android", "--json");

        Assert.Equal(0, result.ExitCode);
        var root = result.ParseJsonOutput();
        Assert.True(root.GetProperty("ok").GetBoolean());
        Assert.Equal("resolve", root.GetProperty("mode").GetString());
        var resolve = root.GetProperty("resolve");
        Assert.Equal("matched", resolve.GetProperty("outcome").GetString());
        Assert.Equal(identity, resolve.GetProperty("requested").GetString());
        Assert.Equal(2, resolve.GetProperty("candidateIdentities").GetInt32());
        var match = Assert.Single(resolve.GetProperty("matches").EnumerateArray().ToList());
        Assert.Equal("checkout.md", match.GetProperty("path").GetString());
        Assert.Equal("android", match.GetProperty("platform").GetString());
        Assert.Equal("committed-flow", match.GetProperty("source").GetString());
    }

    /// <summary>
    /// An issue names a platform, but a reader can paste the wrong one. With no platform the
    /// resolver still only ever compares exact digests - it just computes one per publishable
    /// platform instead of guessing.
    /// </summary>
    [Fact]
    public async Task FlowIdentity_Resolve_WithoutAPlatform_TriesEveryPublishablePlatform()
    {
        var directory = CreateDirectory("resolve-any-platform");
        await WriteFlowAsync(directory, "checkout", "Alpha");
        var identity = await ComputeIdentityAsync(directory, "checkout", "ios");
        var cli = new CliTestHarness(mockAgentPort: 1);

        var result = await cli.InvokeRawAsync(
            "devflow", "flow", "identity", "--resolve", identity, "--search", directory, "--json");

        Assert.Equal(0, result.ExitCode);
        var root = result.ParseJsonOutput();
        Assert.Equal(
            ["android", "ios", "maccatalyst", "windows"],
            root.GetProperty("platforms").EnumerateArray().Select(item => item.GetString()!).ToArray());
        var match = Assert.Single(root.GetProperty("resolve").GetProperty("matches").EnumerateArray().ToList());
        Assert.Equal("ios", match.GetProperty("platform").GetString());
    }

    /// <summary>
    /// The digest covers flow content, so an edit since the run legitimately stops the identity
    /// resolving. That is information, not an error to smooth over: the sidecar still records the
    /// digest the flow had when it last ran, which names the test while stating plainly that this
    /// checkout cannot reproduce it.
    /// </summary>
    [Fact]
    public async Task FlowIdentity_Resolve_WithAFlowEditedSinceTheRun_ReportsSupersededNotAMatch()
    {
        var directory = CreateDirectory("resolve-superseded");
        var flowPath = await WriteFlowAsync(directory, "checkout", "Alpha");
        var identity = await ComputeIdentityAsync(directory, "checkout", "android");
        var recorded = await ComputeFlowDigestAsync(directory, "checkout");
        await WritePlanAsync(directory, "checkout", recorded);
        await WriteFlowAsync(directory, "checkout", "Gamma");
        var current = await ComputeFlowDigestAsync(directory, "checkout");
        Assert.NotEqual(recorded, current);
        var cli = new CliTestHarness(mockAgentPort: 1);

        var result = await cli.InvokeRawAsync(
            "devflow", "flow", "identity", "--resolve", identity, "--search", directory, "--platform", "android", "--json");

        // The working tree does not reproduce the run, so a scripted consumer must not read this
        // as success even though the test has been named.
        Assert.Equal(1, result.ExitCode);
        var root = result.ParseJsonOutput();
        Assert.False(root.GetProperty("ok").GetBoolean());
        var resolve = root.GetProperty("resolve");
        Assert.Equal("matched-superseded", resolve.GetProperty("outcome").GetString());
        var match = Assert.Single(resolve.GetProperty("matches").EnumerateArray().ToList());
        Assert.Equal("checkout.md", match.GetProperty("path").GetString());
        Assert.Equal("plan-sidecar", match.GetProperty("source").GetString());
        Assert.Equal(recorded, match.GetProperty("flowDigest").GetString());
        Assert.Equal(current, match.GetProperty("currentFlowDigest").GetString());
        Assert.False(match.GetProperty("planBindingCurrent").GetBoolean());
        var explanation = string.Join(" ", resolve.GetProperty("explanation").EnumerateArray().Select(item => item.GetString()));
        Assert.Contains("has been edited since the run", explanation, StringComparison.Ordinal);
        Assert.Contains("Check out the commit named in the issue", explanation, StringComparison.Ordinal);
        Assert.True(File.Exists(flowPath));
    }

    /// <summary>
    /// A superseded match rests on the sidecar having been bound to this flow at run time, which
    /// <c>CommittedFlowBundleLoader</c> enforces on both <c>flow.path</c> and <c>flow.digest</c>. A
    /// sidecar copy-pasted from another flow could never have run, so honouring its digest would
    /// name a flow that did not produce the identity - the worst answer this command could give.
    /// </summary>
    [Fact]
    public async Task FlowIdentity_Resolve_WithASidecarBoundToAnotherFlow_ReportsNoMatchNotSuperseded()
    {
        var directory = CreateDirectory("resolve-foreign-sidecar");
        await WriteFlowAsync(directory, "checkout", "Alpha");
        var identity = await ComputeIdentityAsync(directory, "checkout", "android");
        var recorded = await ComputeFlowDigestAsync(directory, "checkout");
        await WriteFlowAsync(directory, "checkout", "Gamma");

        // 'search.md' never had 'checkout.md's digest; its sidecar merely claims it.
        await WriteFlowAsync(directory, "search", "Beta");
        await WritePlanAsync(directory, "search", recorded, boundPath: "checkout.md");
        var cli = new CliTestHarness(mockAgentPort: 1);

        var result = await cli.InvokeRawAsync(
            "devflow", "flow", "identity", "--resolve", identity, "--search", directory, "--platform", "android", "--json");

        Assert.Equal(1, result.ExitCode);
        var resolve = result.ParseJsonOutput().GetProperty("resolve");
        Assert.Equal("no-match", resolve.GetProperty("outcome").GetString());
        Assert.Empty(resolve.GetProperty("matches").EnumerateArray());
    }

    /// <summary>
    /// The document promises that "no match" never silently means "stopped looking", so a sidecar
    /// the command could not read has to be counted and named rather than dropped.
    /// </summary>
    [Fact]
    public async Task FlowIdentity_Resolve_WithAnUnreadableSidecar_ReportsItAsASkip()
    {
        var directory = CreateDirectory("resolve-broken-sidecar");
        await WriteFlowAsync(directory, "checkout", "Alpha");
        await File.WriteAllTextAsync(Path.Combine(directory, "checkout.maui-plan.json"), "{ this is not json");
        var identity = FlowIdentityCommands.ComputeTestIdentity("android", "tier-1", new string('a', 64));
        var cli = new CliTestHarness(mockAgentPort: 1);

        var result = await cli.InvokeRawAsync(
            "devflow", "flow", "identity", "--resolve", identity, "--search", directory, "--platform", "android", "--json");

        Assert.Equal(1, result.ExitCode);
        var root = result.ParseJsonOutput();
        var scan = root.GetProperty("scan");
        Assert.Equal(1, scan.GetProperty("skippedTotal").GetInt32());
        var skip = Assert.Single(scan.GetProperty("skipped").EnumerateArray().ToList());
        Assert.Equal("checkout.maui-plan.json", skip.GetProperty("path").GetString());
        Assert.Equal("plan-sidecar-unreadable", skip.GetProperty("reason").GetString());

        var explanation = string.Join(
            " ", root.GetProperty("resolve").GetProperty("explanation").EnumerateArray().Select(item => item.GetString()));
        Assert.Contains("could not be read", explanation, StringComparison.Ordinal);
    }

    /// <summary>
    /// The scan refuses rather than truncating, because a resolver that quietly stopped scanning
    /// would answer "no match" for a flow it never looked at.
    /// </summary>
    [Fact]
    public async Task FlowIdentity_Resolve_WithASearchRootTooLargeToScanExhaustively_Refuses()
    {
        var directory = CreateDirectory("resolve-too-large");
        for (var index = 0; index <= 4096; index++)
            await File.WriteAllTextAsync(Path.Combine(directory, $"note-{index:0000}.md"), "# Not a flow");
        var identity = FlowIdentityCommands.ComputeTestIdentity("android", "tier-1", new string('a', 64));
        var cli = new CliTestHarness(mockAgentPort: 1);

        var result = await cli.InvokeRawAsync(
            "devflow", "flow", "identity", "--resolve", identity, "--search", directory, "--platform", "android", "--json");

        Assert.Equal(1, result.ExitCode);
        Assert.Contains("\"type\":\"search-root-too-large\"", result.StdErr, StringComparison.Ordinal);
    }

    /// <summary>
    /// A current sidecar records the same digest as the flow, so it can never turn an unrelated
    /// identity into a superseded "match". Exact or nothing.
    /// </summary>
    [Fact]
    public async Task FlowIdentity_Resolve_WithNoMatch_ExplainsTheLikelyCausesAndFails()
    {
        var directory = CreateDirectory("resolve-no-match");
        await WriteFlowAsync(directory, "checkout", "Alpha");
        await WritePlanAsync(directory, "checkout", await ComputeFlowDigestAsync(directory, "checkout"));
        var cli = new CliTestHarness(mockAgentPort: 1);

        var result = await cli.InvokeRawAsync(
            "devflow", "flow", "identity",
            "--resolve", "sha256:" + new string('4', 64),
            "--search", directory, "--platform", "android", "--json");

        Assert.Equal(1, result.ExitCode);
        var root = result.ParseJsonOutput();
        Assert.False(root.GetProperty("ok").GetBoolean());
        var resolve = root.GetProperty("resolve");
        Assert.Equal("no-match", resolve.GetProperty("outcome").GetString());
        Assert.Empty(resolve.GetProperty("matches").EnumerateArray());
        var explanation = resolve.GetProperty("explanation").EnumerateArray().Select(item => item.GetString()!).ToList();
        Assert.Contains(explanation, line => line.Contains("edited after the run", StringComparison.Ordinal));
        Assert.Contains(explanation, line => line.Contains("platform is wrong", StringComparison.Ordinal));
        Assert.Contains(explanation, line => line.Contains("tier is wrong", StringComparison.Ordinal));
        Assert.Contains(explanation, line => line.Contains("outside the search root", StringComparison.Ordinal));
    }

    [Fact]
    public async Task FlowIdentity_Resolve_LeavesEveryScannedFileUntouched()
    {
        var directory = CreateDirectory("read-only");
        await WriteFlowAsync(directory, "checkout", "Alpha");
        await WritePlanAsync(directory, "checkout", await ComputeFlowDigestAsync(directory, "checkout"));
        var before = Snapshot(directory);
        var cli = new CliTestHarness(mockAgentPort: 1);

        await cli.InvokeRawAsync(
            "devflow", "flow", "identity",
            "--resolve", "sha256:" + new string('7', 64),
            "--search", directory, "--json");

        Assert.Equal(before, Snapshot(directory));
    }

    [Fact]
    public async Task FlowIdentity_Resolve_WithAMalformedIdentity_RefusesRatherThanScanning()
    {
        var cli = new CliTestHarness(mockAgentPort: 1);

        var result = await cli.InvokeRawAsync(
            "devflow", "flow", "identity", "--resolve", "sha256:not-a-digest", "--search", _root, "--json");

        Assert.Equal(1, result.ExitCode);
        Assert.Contains("\"type\":\"identity-invalid\"", result.StdErr, StringComparison.Ordinal);
    }

    /// <summary>
    /// The handoff envelope lets a reader see a wider platform set than the producer can ever emit
    /// an identity for. Accepting one of those extra values would hand back a well-formed digest
    /// that can never appear in an issue, so they are refused alongside outright unknown values.
    /// </summary>
    [Theory]
    [InlineData("tizen")]
    [InlineData("macos")]
    [InlineData("cross-platform")]
    [InlineData("unknown")]
    public async Task FlowIdentity_WithAPlatformCiCannotPublish_Refuses(string platform)
    {
        var directory = CreateDirectory("bad-platform-" + platform);
        await WriteFlowAsync(directory, "checkout", "Alpha");
        var cli = new CliTestHarness(mockAgentPort: 1);

        var result = await cli.InvokeRawAsync(
            "devflow", "flow", "identity", directory, "--platform", platform, "--json");

        Assert.Equal(1, result.ExitCode);
        Assert.Contains("\"type\":\"platform-invalid\"", result.StdErr, StringComparison.Ordinal);
    }

    /// <summary>
    /// A tier carrying a newline would add fields to the hashed construction and could report a
    /// collision as a match, so it is refused rather than hashed.
    /// </summary>
    [Fact]
    public async Task FlowIdentity_WithATierThatCouldInjectConstructionFields_Refuses()
    {
        var directory = CreateDirectory("bad-tier");
        await WriteFlowAsync(directory, "checkout", "Alpha");
        var cli = new CliTestHarness(mockAgentPort: 1);

        var result = await cli.InvokeRawAsync(
            "devflow", "flow", "identity", directory, "--tier", "tier-1\nandroid\ntier-1", "--json");

        Assert.Equal(1, result.ExitCode);
        Assert.Contains("\"type\":\"tier-invalid\"", result.StdErr, StringComparison.Ordinal);
    }

    [Fact]
    public async Task FlowIdentity_WithoutAPathInComputeMode_Refuses()    {
        var cli = new CliTestHarness(mockAgentPort: 1);

        var result = await cli.InvokeRawAsync("devflow", "flow", "identity", "--json");

        Assert.Equal(1, result.ExitCode);
        Assert.Contains("\"type\":\"flow-path-required\"", result.StdErr, StringComparison.Ordinal);
    }

    /// <summary>
    /// A directory of ordinary Markdown is the normal case for a repository search root. Prose is
    /// counted separately from documents that looked like a flow and could not be read as one, so
    /// "no match" is never explained by a scan that quietly discarded the answer.
    /// </summary>
    [Fact]
    public async Task FlowIdentity_Scan_SeparatesProseFromUnreadableFlows()
    {
        var directory = CreateDirectory("scan");
        await WriteFlowAsync(directory, "checkout", "Alpha");
        await File.WriteAllTextAsync(Path.Combine(directory, "README.md"), "# Notes\n\nOrdinary prose.\n");
        await File.WriteAllTextAsync(
            Path.Combine(directory, "broken.md"),
            "# Broken\n\n```json maui-test\n{ not json\n```\n");
        var cli = new CliTestHarness(mockAgentPort: 1);

        var result = await cli.InvokeRawAsync("devflow", "flow", "identity", directory, "--platform", "android", "--json");

        Assert.Equal(0, result.ExitCode);
        var scan = result.ParseJsonOutput().GetProperty("scan");
        Assert.Equal(3, scan.GetProperty("markdownFiles").GetInt32());
        Assert.Equal(1, scan.GetProperty("flows").GetInt32());
        Assert.Equal(1, scan.GetProperty("nonFlowDocuments").GetInt32());
        Assert.Equal(1, scan.GetProperty("skippedTotal").GetInt32());
        var skipped = Assert.Single(scan.GetProperty("skipped").EnumerateArray().ToList());
        Assert.Equal("broken.md", skipped.GetProperty("path").GetString());
        Assert.Equal("flow-unparseable", skipped.GetProperty("reason").GetString());
    }

    [Fact]
    public async Task FlowIdentity_HumanOutput_StatesTheOutcomeAndTheScanItRestsOn()
    {
        var directory = CreateDirectory("human");
        await WriteFlowAsync(directory, "checkout", "Alpha");
        var identity = await ComputeIdentityAsync(directory, "checkout", "android");
        var cli = new CliTestHarness(mockAgentPort: 1);

        var result = await cli.InvokeRawAsync(
            "devflow", "flow", "identity", "--resolve", identity, "--search", directory, "--platform", "android", "--no-json");

        Assert.Equal(0, result.ExitCode);
        Assert.Contains("Outcome: matched", result.StdOut, StringComparison.Ordinal);
        Assert.Contains("checkout.md", result.StdOut, StringComparison.Ordinal);
        Assert.Contains("Scanned 1 Markdown file(s)", result.StdOut, StringComparison.Ordinal);
    }

    private string CreateDirectory(string name)
    {
        var directory = Path.Combine(_root, name);
        Directory.CreateDirectory(directory);
        return directory;
    }

    private static async Task<string> WriteFlowAsync(string directory, string name, string automationId)
    {
        var path = Path.Combine(directory, name + ".md");
        var markdown = $$"""
        # Scenario: {{name}}

        ```json maui-test
        {
          "schema": 2,
          "name": "{{name}}",
          "app": "com.example.identityfixture",
          "platform": "android",
          "steps": [
            {
              "seq": 1,
              "action": "tap",
              "args": { "selector": { "automationId": "{{automationId}}" } }
            }
          ]
        }
        ```
        """;
        await File.WriteAllTextAsync(path, markdown);
        return path;
    }

    private static async Task WritePlanAsync(
        string directory,
        string name,
        string flowDigest,
        string? boundPath = null)
    {
        var path = Path.Combine(directory, name + ".maui-plan.json");
        var json = $$"""
        {
          "schema": 1,
          "planId": "plan-{{name}}",
          "revision": 1,
          "flow": {
            "path": "{{boundPath ?? name + ".md"}}",
            "digest": "{{flowDigest[7..]}}"
          },
          "title": "{{name}}",
          "goal": "Replay the committed {{name}} flow.",
          "sideEffectPolicy": "none"
        }
        """;
        await File.WriteAllTextAsync(path, json);
    }

    private static async Task<string> ComputeFlowDigestAsync(string directory, string name)
    {
        var result = await FlowIdentityCommands.ExecuteAsync(
            Path.Combine(directory, name + ".md"), resolve: null, search: null, platform: "android", tier: "tier-1");
        return Assert.Single(result.Flows).FlowDigest;
    }

    private static async Task<string> ComputeIdentityAsync(string directory, string name, string platform)
        => FlowIdentityCommands.ComputeTestIdentity(platform, "tier-1", await ComputeFlowDigestAsync(directory, name));

    private static string Sha256Text(string text)
        => "sha256:" + Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(text))).ToLowerInvariant();

    private static List<string> Snapshot(string directory)
        => Directory.GetFiles(directory, "*", SearchOption.AllDirectories)
            .OrderBy(static path => path, StringComparer.Ordinal)
            .Select(static path =>
                $"{Path.GetFileName(path)}:{Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path)))}")
            .ToList();

    /// <summary>
    /// Lifts the producer's own hashing functions out of the committed script with the PowerShell
    /// parser and calls <c>Get-TestIdentity</c>, so the assertion is against the exact text CI
    /// runs. Returns null when pwsh is unavailable.
    /// </summary>
    private async Task<string?> RunProducerIdentityAsync(
        string script, string platform, string tier, string flowDigest)
    {
        // Driven through -File rather than -Command: -Command re-parses the joined argument
        // tokens, which mangles a multi-line harness before PowerShell ever runs it.
        var harnessPath = Path.Combine(_root, "producer-identity-harness.ps1");
        if (!File.Exists(harnessPath))
        {
            await File.WriteAllTextAsync(harnessPath, """
                param(
                    [Parameter(Mandatory)] [string] $ScriptPath,
                    [Parameter(Mandatory)] [string] $Platform,
                    [Parameter(Mandatory)] [string] $Tier,
                    [Parameter(Mandatory)] [string] $FlowDigest
                )

                $tokens = $null
                $errors = $null
                $ast = [System.Management.Automation.Language.Parser]::ParseFile($ScriptPath, [ref] $tokens, [ref] $errors)
                if ($errors -and $errors.Count -gt 0) { throw 'producer-parse-failed' }
                foreach ($name in @('Get-Sha256Bytes', 'Get-Sha256Text', 'Get-TestIdentity')) {
                    $found = $ast.FindAll({
                        param($node)
                        $node -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $node.Name -eq $name
                    }, $true)
                    if ($found.Count -ne 1) { throw "producer-function-missing:$name" }
                    . ([scriptblock]::Create($found[0].Extent.Text))
                }
                Write-Output (Get-TestIdentity -Platform $Platform -Tier $Tier -FlowDigest $FlowDigest)
                """);
        }

        using var process = new Process
        {
            StartInfo = new ProcessStartInfo(OperatingSystem.IsWindows() ? "pwsh.exe" : "pwsh")
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
            },
        };
        process.StartInfo.ArgumentList.Add("-NoLogo");
        process.StartInfo.ArgumentList.Add("-NoProfile");
        process.StartInfo.ArgumentList.Add("-File");
        process.StartInfo.ArgumentList.Add(harnessPath);
        process.StartInfo.ArgumentList.Add("-ScriptPath");
        process.StartInfo.ArgumentList.Add(script);
        process.StartInfo.ArgumentList.Add("-Platform");
        process.StartInfo.ArgumentList.Add(platform);
        process.StartInfo.ArgumentList.Add("-Tier");
        process.StartInfo.ArgumentList.Add(tier);
        process.StartInfo.ArgumentList.Add("-FlowDigest");
        process.StartInfo.ArgumentList.Add(flowDigest);

        try
        {
            process.Start();
        }
        catch (Exception ex) when (ex is System.ComponentModel.Win32Exception or PlatformNotSupportedException)
        {
            return null;
        }

        var stdoutTask = process.StandardOutput.ReadToEndAsync();
        var stderrTask = process.StandardError.ReadToEndAsync();
        await Task.WhenAll(stdoutTask, stderrTask);
        var stdout = await stdoutTask;
        var stderr = await stderrTask;
        await process.WaitForExitAsync();
        Assert.True(process.ExitCode == 0, $"The producer harness failed: {stderr}");
        return stdout.Trim();
    }

    private static string FindRepositoryRoot()
    {
        for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory is not null; directory = directory.Parent)
        {
            if (File.Exists(Path.Combine(directory.FullName, "MauiLabs.slnx")))
                return directory.FullName;
        }
        throw new InvalidOperationException("Repository root was not found.");
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_root))
                Directory.Delete(_root, recursive: true);
        }
        catch (IOException)
        {
        }
    }
}
