using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.Maui.DevFlow.Analyzers;

/// <summary>
/// Incremental generator that emits a per-assembly <c>IXamlSourceMapProvider</c> mapping each
/// XAML-defined type (its <c>x:Class</c>) to the raw text and original path of its <c>.xaml</c>
/// file, plus a <c>[ModuleInitializer]</c> that registers the provider with
/// <c>XamlSourceMapRegistry</c>. The runtime parser (<c>XamlSourceMap.Parse</c>) turns the embedded
/// text into child-path → source-position entries on demand, so DevFlow's visual tree can carry
/// sourceFile/sourceLine for click-to-XAML.
/// </summary>
/// <remarks>
/// Only <c>.xaml</c> <c>AdditionalFiles</c> carrying <c>build_metadata.AdditionalFiles.DevFlowXaml =
/// true</c> are consumed — the DevFlow build targets promote <c>@(MauiXaml)</c> into that set only
/// when <c>$(DevFlowXamlSourceMapsEnabled)</c> is on (Debug by default), so Release/AOT/store builds
/// embed no source text and no developer paths.
/// <para>
/// The embedded text is a <em>build-time snapshot</em>: line numbers are valid for the XAML as it
/// was compiled. If the developer edits the .xaml after launch (or XAML Hot Reload changes it), the
/// map can point at a stale line until the app is rebuilt. A future enhancement can emit a content
/// hash so the consumer verifies the current file before navigating (see the m5c follow-on).
/// </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class XamlSourceMapGenerator : IIncrementalGenerator
{
    private const string XamlMarkerMetadata = "build_metadata.AdditionalFiles.DevFlowXaml";

    // Both the modern (2009) and legacy (2006) XAML namespaces expose x:Class.
    private static readonly XName[] ClassAttributeNames =
    {
        XName.Get("Class", "http://schemas.microsoft.com/winfx/2009/xaml"),
        XName.Get("Class", "http://schemas.microsoft.com/winfx/2006/xaml"),
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select(static (pair, ct) => TryReadXaml(pair.Left, pair.Right, ct))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value);

        context.RegisterSourceOutput(models.Collect(), static (spc, items) => Emit(spc, items));
    }

    private static XamlModel? TryReadXaml(AdditionalText file, AnalyzerConfigOptionsProvider optionsProvider, System.Threading.CancellationToken ct)
    {
        var options = optionsProvider.GetOptions(file);
        if (!options.TryGetValue(XamlMarkerMetadata, out var marker) ||
            !string.Equals(marker, "true", System.StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        if (!file.Path.EndsWith(".xaml", System.StringComparison.OrdinalIgnoreCase))
            return null;

        var text = file.GetText(ct)?.ToString();
        if (string.IsNullOrWhiteSpace(text))
            return null;

        var fullTypeName = TryReadClass(text!);
        if (fullTypeName is null)
            return null;

        return new XamlModel(fullTypeName, file.Path, text!);
    }

    private static string? TryReadClass(string xaml)
    {
        XDocument doc;
        try
        {
            doc = XDocument.Parse(xaml);
        }
        catch (System.Xml.XmlException)
        {
            return null;
        }

        var root = doc.Root;
        if (root is null)
            return null;

        foreach (var name in ClassAttributeNames)
        {
            var value = root.Attribute(name)?.Value;
            if (!string.IsNullOrWhiteSpace(value))
                return value!.Trim();
        }

        return null;
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<XamlModel> items)
    {
        if (items.IsDefaultOrEmpty)
            return;

        // Deduplicate by type name (first declaration wins) so a repeated x:Class can't emit twice.
        var unique = new Dictionary<string, XamlModel>(System.StringComparer.Ordinal);
        foreach (var item in items)
        {
            if (!unique.ContainsKey(item.FullTypeName))
                unique[item.FullTypeName] = item;
        }

        if (unique.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Microsoft.Maui.DevFlow.Agent.Core.SourceMapping.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"Microsoft.Maui.DevFlow.Analyzers\", \"1.0.0\")]");
        sb.AppendLine("    internal sealed class __DevFlowXamlSourceMapProvider : global::Microsoft.Maui.DevFlow.Agent.Core.SourceMapping.IXamlSourceMapProvider");
        sb.AppendLine("    {");
        sb.AppendLine("        private static readonly global::System.Collections.Generic.Dictionary<string, (string File, string Xaml)> _sources =");
        sb.AppendLine("            new global::System.Collections.Generic.Dictionary<string, (string, string)>(global::System.StringComparer.Ordinal)");
        sb.AppendLine("        {");
        foreach (var model in unique.Values)
        {
            var key = SymbolDisplay.FormatLiteral(model.FullTypeName, quote: true);
            var path = SymbolDisplay.FormatLiteral(model.Path, quote: true);
            var xaml = SymbolDisplay.FormatLiteral(model.Xaml, quote: true);
            sb.AppendLine($"            [{key}] = ({path}, {xaml}),");
        }
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        private readonly global::System.Collections.Concurrent.ConcurrentDictionary<string, global::Microsoft.Maui.DevFlow.Agent.Core.SourceMapping.XamlSourceMap> _cache =");
        sb.AppendLine("            new global::System.Collections.Concurrent.ConcurrentDictionary<string, global::Microsoft.Maui.DevFlow.Agent.Core.SourceMapping.XamlSourceMap>(global::System.StringComparer.Ordinal);");
        sb.AppendLine();
        sb.AppendLine("        public global::Microsoft.Maui.DevFlow.Agent.Core.SourceMapping.XamlSourceMap? GetMap(string fullTypeName)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_cache.TryGetValue(fullTypeName, out var cached)) return cached;");
        sb.AppendLine("            if (!_sources.TryGetValue(fullTypeName, out var entry)) return null;");
        sb.AppendLine("            var map = global::Microsoft.Maui.DevFlow.Agent.Core.SourceMapping.XamlSourceMap.Parse(entry.Xaml, entry.File);");
        sb.AppendLine("            if (map is not null) _cache[fullTypeName] = map;");
        sb.AppendLine("            return map;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    internal static class __DevFlowXamlSourceMapModuleInit");
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void Initialize()");
        sb.AppendLine("            => global::Microsoft.Maui.DevFlow.Agent.Core.SourceMapping.XamlSourceMapRegistry.Register(new __DevFlowXamlSourceMapProvider());");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("DevFlowXamlSourceMaps.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private readonly record struct XamlModel(string FullTypeName, string Path, string Xaml);
}
